Fix missing include pcap/pcap.h in input raw plugin
Fixes the following error when building with gcc 15 on Alpine Linux:

    In file included from src/plugins/input/raw/src/raw.cpp:15:
    src/plugins/input/raw/src/raw.hpp:153:6: error: variable or field 'packet_handler' declared void
      153 | void packet_handler(u_char* arg, const struct pcap_pkthdr* h, const u_char* data);
          |      ^~~~~~~~~~~~~~
    src/plugins/input/raw/src/raw.hpp:153:21: error: 'u_char' was not declared in this scope; did you mean 'putchar'?
      153 | void packet_handler(u_char* arg, const struct pcap_pkthdr* h, const u_char* data);
          |                     ^~~~~~
          |                     putchar
    src/plugins/input/raw/src/raw.hpp:153:29: error: 'arg' was not declared in this scope
      153 | void packet_handler(u_char* arg, const struct pcap_pkthdr* h, const u_char* data);
          |                             ^~~
    src/plugins/input/raw/src/raw.hpp:153:34: error: expected primary-expression before 'const'
      153 | void packet_handler(u_char* arg, const struct pcap_pkthdr* h, const u_char* data);
          |                                  ^~~~~
    src/plugins/input/raw/src/raw.hpp:153:63: error: expected primary-expression before 'const'
      153 | void packet_handler(u_char* arg, const struct pcap_pkthdr* h, const u_char* data);
          |                                                               ^~~~~